version: '3'

services:

  laravel:
    container_name: laravel
    image: felipenasci/laravel:latest
    networks:
      - laranet

  nginx:
    container_name: nginx
    image: felipenasci/reverse-proxy
    ports:
      - 8080:80
    expose:
      - 8080
    networks:
      - laranet
    depends_on:
      - laravel

networks:
  laranet:
    driver: bridge