version: '3'

services:
  app:
    build: 
      context: node-app
    container_name: node-app
    restart: always
    tty: true    
    depends_on: 
      - database
    ports:
      - 3000:3000
    networks:
      - node-network
  
  nginx:
    build: 
      context: nginx
    container_name: nginx-proxy
    restart: always
    tty: true    
    depends_on: 
    - app
    - database
    ports:
      - 8081:80
    networks:
      - node-network

  database:
    container_name: my-sql
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./node-app/data:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=example
    networks:
      - node-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
