name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fullcycle-notes

    steps:
      - uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Docs
        run: yarn gen:docs

      - name: Build app
        run: yarn build

      - name: Deploy App
        env:
          GIT_USER: ${{ secrets.GH_TOKEN }}
          GIT_USER_NAME: felipenasci
          GIT_USER_EMAIL: dfnascimento@live.com
        run: yarn deploy
