name: ci-golang-workflow
on: [push]

jobs:
  check-golang-app:
    strategy:
      matrix:
        go: ["1.15", "1.14"]
        so: ["ubuntu-20.04", "ubuntu-latest"]

    runs-on: ${{ matrix.so }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: show version
        run: go version
      - name: run tests
        run: go test ./continuos-integration/go-app
      - run: go run ./continuos-integration/go-app
