name: ci-golang-workflow
on: [push]

jobs:
  check-golang-app:
    strategy:
      matrix:
        go: ["1.15", "1.14"]
        so: ["ubuntu-20.04", "ubuntu-latest"]

    runs-on: ${{ matrix.so }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: show version
        run: go version
      - name: run tests
        run: go test ./continuos-integration/go-app
      - run: go run ./continuos-integration/go-app

  docker-action:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./continuos-integration/docker-actions
          file: ./continuos-integration/docker-actions/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-app:latest